SELECT
    LAND_USE_DESCRIPTION,
    COUNT(*) AS TOTAL_PROPERTIES,
    AVG(TOTAL_APPRAISED_VALUE) AS AVERAGE_APPRAISED_VALUE,
    MIN(TOTAL_APPRAISED_VALUE) AS MINIMUM_APPRAISED_VALUE,
    MAX(TOTAL_APPRAISED_VALUE) AS MAXIMUM_APPRAISED_VALUE
FROM {{ ref('silver_nashville_housing_property_data') }}
WHERE LAND_USE_DESCRIPTION IS NOT NULL
GROUP BY LAND_USE_DESCRIPTION
ORDER BY TOTAL_PROPERTIES DESC