SELECT
    PROPERTY_CITY,
    COUNT(*) AS TOTAL_PROPERTIES,
    AVG(TOTAL_APPRAISED_VALUE) AS AVERAGE_APPRAISED_VALUE
FROM {{ ref('silver_nashville_housing_property_data') }}
WHERE PROPERTY_CITY IS NOT NULL
GROUP BY PROPERTY_CITY
ORDER BY TOTAL_PROPERTIES DESC