SELECT
    RECORD_DATA:attributes.APN::STRING AS APN,
    RECORD_DATA:attributes.ParID::STRING AS PARCEL_ID,
    RECORD_DATA:attributes.Owner::STRING AS OWNER_NAME,
    RECORD_DATA:attributes.PropAddr::STRING AS PROPERTY_ADDRESS,
    RECORD_DATA:attributes.PropCity::STRING AS PROPERTY_CITY,
    RECORD_DATA:attributes.PropState::STRING AS PROPERTY_STATE,
    RECORD_DATA:attributes.PropZip::STRING AS PROPERTY_ZIP_CODE,
    RECORD_DATA:attributes.LUCode::STRING AS LAND_USE_CODE,
    RECORD_DATA:attributes.LUDesc::STRING AS LAND_USE_DESCRIPTION,
    RECORD_DATA:attributes.Acres::FLOAT AS ACRES,
    RECORD_DATA:attributes.SalePrice::FLOAT AS SALE_PRICE,
    RECORD_DATA:attributes.LandAppr::FLOAT AS LAND_APPRAISED_VALUE,
    RECORD_DATA:attributes.ImprAppr::FLOAT AS IMPROVEMENT_APPRAISED_VALUE,
    RECORD_DATA:attributes.TotlAppr::FLOAT AS TOTAL_APPRAISED_VALUE,
    RECORD_DATA:attributes.TaxDist::STRING AS TAX_DISTRICT,
    RECORD_DATA:attributes.Council::STRING AS COUNCIL_DISTRICT,
    RECORD_DATA:attributes.Tract::STRING AS CENSUS_TRACT
FROM {{ source('raw_data', 'BRONZE_NASHVILLE_HOUSING_PROPERTY_DATA') }}